inherit_from: .rubocop_todo.yml

require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance

AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  Exclude:
    - 'bin/**/*'
    - 'db/schema.rb'
    - 'db/migrate/**/*'  # 変更が多くスタイル拘束の必要性が低い
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - 'tmp/**/*'

Layout/LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'  # RSpecはブロックが長くなりやすいため

RSpec/ExampleLength:
  Max: 12

# Rails推奨だが、段階的に
Rails/UnknownEnv:
  Enabled: true
inherit_from:
  - .rubocop_todo.yml

# 導入直後のため、現状について固定
AllCops:
  NewCops: enable
  SuggestExtensions: false  # ← RuboCopの提案メッセージを黙らせたい場合
  Exclude:
    - 'bin/**/*'
    - 'db/schema.rb'
    - 'db/migrate/**/*'
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - 'tmp/**/*'
