inherit_from:
  - .rubocop_todo.yml

# 継承時に配列をマージ（Excludeが上書きされないように）
inherit_mode:
  merge:
    - Exclude

plugins:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance

AllCops:
  NewCops: enable
  SuggestExtensions: false     # 提案メッセージ抑制（任意）
  TargetRubyVersion: 3.2
  Exclude:
    - 'bin/**/*'
    - 'db/schema.rb'
    - 'db/migrate/**/*'
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - 'tmp/**/*'

Layout/LineLength:
  Max: 120
  # Exclude:
  #   - 'config/initializers/devise.rb'  # 例：長文コメント除外したい場合

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'   # RSpecは長くなりがち

RSpec/ExampleLength:
  Max: 12

# 段階的に導入
Rails/UnknownEnv:
  Enabled: true
